### ISSUE TITLE
 应该是"一边享受这商业程序员的物质舒适(有钱呗),一边写着没人会看的到的代码

### ISSUE THREAD

**Issue by royaso** [lifanxi/free-as-in-freedom-zh-cn#10]
397 Hence the importance of the laser printer and the encounter that resulted from it. Without it,     Stallman says, his life might have followed a more ordinary path, one balancing the material     comforts of a commercial programmer with the ultimate frustration of a life spent writing invi    sible software code. There would have been no sense of clarity, no urgency to address a proble    m others weren't addressing. Most importantly, there would have been no righteous anger, an em    otion that, as we soon shall see, has propelled Stallman's career as surely as any political i    deology or ethical belief.
398 \fi
399 
400 \ifdefined\chs
401 打印机事件的重要意义恰在于此。正如斯托曼所言，倘若没有这次事件，他的人生也许就会落入平常，纠结
    着，一边开发专有软件，一边痛苦地编写没人会看到的代码。当然也不会有着如今清晰的思路，更不会去解
    决别人沿未想过的各种问题。最重要的，他心中也不会再有那份不平，推动着他去追求他的政治理想和道德
    信仰。
------------------
其他都很好,就一点有错

一边开发专有软件，一边痛苦地编写没人会看到的代码

这个"一边...一边..."的用法明显不对啊,两个一边都是同一个意思啊

应该是"一边享受这商业程序员的物质舒适(有钱呗),一边写着没人会看的到的代码

**Comment by lifanxi** [comment]
这里的错辞可以进行一些调整，等处理第二版时再修改。

谢谢指正。
