### ISSUE TITLE
chapter 10, line 354

### ISSUE THREAD

**Issue by kumakichi** [lifanxi/free-as-in-freedom-zh-cn#14]
https://github.com/lifanxi/free-as-in-freedom-zh-cn/blob/master/chap10.tex#L354

有几句没翻译，默多克和rms对于程序包含调试信息那几句

**Comment by kumakichi** [comment]
而且

`实事求是的说，理查德是一个很与之合作的人。`

应当翻译为

`实事求是的说，理查德是一个很不好与之合作的人。`

更合适吧

**Comment by kumakichi** [comment]
https://github.com/lifanxi/free-as-in-freedom-zh-cn/blob/master/chap10.tex#L427

`试图讨好斯托曼但后来又厌恶斯托曼的徽管理风格的`这句怎么来的虽然不明白，但是觉得其中的`徽管理风格`应当是个typo，应作`微管理风格`

**Comment by lifanxi** [comment]
谢谢指正。

master分支上的内容其实还没有完成翻译，部分完成的也还没有进行校对，有些第一版中校对过的也还没合回master分支，所以问题会比较多。v1分支上的内容才是实际出版的书上的内容。

你指出的问题我晚些时候会进行修正。同时也欢迎你直接修改有问题的部分，并提交Pull Request，那样效率可能会比通过Issue指出问题更便捷。
