### ISSUE TITLE
chap04文本错误

### ISSUE THREAD

**Issue by XinArkh** [lifanxi/free-as-in-freedom-zh-cn#17]
https://github.com/lifanxi/free-as-in-freedom-zh-cn/blob/d83a4bd6e2841e70c7b6bf1bfe1bf00bf357fedc/chap04.tex#L158

此处中文翻译最后部分有多余字眼，导致语句不通顺，结合英文原文来看，应属于打字错误。下方加粗部分，第一个“有”字应删除。

> ……他显然不喜欢战争，至少不喜欢这次在东南亚的战争。当然这也并不意味着**就有会有个**姑娘愿意与他一起共度春宵。

另外对翻译文本的改善有一个小建议，“共度春宵”本身含有“一起”的意义，可将“一起共度春宵”中的“一起”删去。

**Comment by lifanxi** [comment]
由于目前GitHub上的仓库中的版本是以纸质书的版本内容为准的，所以暂时不对GitHub仓库中的代码做修正。
已经在主页堪误表上进行了登记：https://www.freemindworld.com/faif　
感谢指正。
