### ISSUE TITLE
翻译内容和已出版的书籍有些差异

### ISSUE THREAD

**Issue by zryfish** [lifanxi/free-as-in-freedom-zh-cn#7]
什么时候能够更新下repo，已出版的书籍有些typo，想反馈下

**Comment by lifanxi** [comment]
谢谢支持。

目前v1分支上的内容已经基本上与出版的版本同步完，可以直接在上面做改动。

我己经发现的错误都已经在 http://faifchs.github.io/index.html 上列出，后续我会以逐个commit的方式把这些bugfix更新到源代码上。
